name: GuessTheNumber
version: 2.1.1
api: 2.0.0
main: SalmonDE\Number
description: Guessing Game for your Server!
author: SalmonDE
website: https://salmonde.de/
commands:
 guessgame:
  description: Main command of GuessTheNumber
  usage: /guessgame <normal|square|plus|minus|abort|solution>
  permission: guessthenumber.cmd
permissions:
 guessthenumber:
  description: Main Permission Node
  children:
   guessthenumber.cmd:
   guessthenumber.normal:
    description: Permission for "/guessgame normal"
   guessthenumber.square:
    description: Permission for "/guessgame square"
   guessthenumber.plus:
     description: Permission for "/guessgame plus"
   guessthenumber.minus:
     description: Permission for "/guessgame minus"
   guessthenumber.solution:
    description: Permission for "/guessgame solution"
   guessthenumber.abort:
    description: Permission for "/guessgame abort"
